services:
  backend:
    image: ghcr.io/torifo/meme-fortress-backend:latest
    container_name: meme-fortress-backend
    restart: unless-stopped
    networks:
      - default
      - global-proxy-network
    expose:
      - "8787"
    volumes:
      - data:/app/data
    environment:
      - RUST_LOG=info
      - VIRTUAL_HOST=api.meme-fortress.riumu.net
      - VIRTUAL_PORT=8787
      - LETSENCRYPT_HOST=api.meme-fortress.riumu.net
      - LETSENCRYPT_EMAIL=akito.shoji@geniee.co.jp

  frontend:
    image: ghcr.io/torifo/meme-fortress-frontend:latest
    container_name: meme-fortress-frontend
    restart: unless-stopped
    networks:
      - global-proxy-network
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=meme-fortress-www.riumu.net
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=meme-fortress-www.riumu.net
      - LETSENCRYPT_EMAIL=akito.shoji@geniee.co.jp

networks:
  global-proxy-network:
    external: true

volumes:
  data:
